/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // gettingStartedSidebar: [
  //   {
  //     type: 'category', 
  //     label: 'Overview',
  //     link: {type: 'doc', id: "overview/overview"},
  //     items: [
  //       {
  //         type: "doc", 
  //         id: "overview/primitives"
  //       },
  //       {
  //         type: "doc", 
  //         id: "overview/services"
  //       },
  //       {
  //         type: "doc", 
  //         id: "overview/technical-support"
  //       }
  //     ]
  //   }
  // ],
  gettingStartedSidebar: [
    {
      type: "autogenerated", 
      dirName: "getting-started"
    }
  ],
  referenceSidebar: [
    {
      type: 'autogenerated', 
      dirName: "reference"
    }
  ],
  guidesSidebar: [
    {
      type: 'category', 
      label: "Overview", 
      link: {type: 'doc', id: "guides/guides"},
      items: [
        {
          type: "doc", 
          id: "guides/debugging-two-way-console"
        },
        {
          type: "doc", 
          id: "guides/aurora-db"
        },
        {
          type: "doc", 
          id: "guides/backblaze"
        },
        {
          type: "doc",
          id: "guides/gpu"
        }
      ]
    }
  ]
  // gettingStartedSidebar: [
  //   {
  //     type: "doc",
  //     id: "overview/overview"
  //   }, 
  //   {
  //     type: "doc", 
  //     id: "overview/primitives"
  //   },
  //   {
  //     type: "doc", 
  //     id: "overview/services"
  //   },
  //   {
  //     type: "doc", 
  //     id: "overview/technical-support"
  //   }
  // ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
