---
sidebar_label: Dockerfile
sidebar_position: 3
---

import { AutoTable } from "../../components/autotable";
import { Details } from "../../components/images/origins/origin-details";

import ImageOriginTypes from "../../components/images/origintype";
import ImageOriginDetails from "../../components/images/origindetails";
import { RemoteRepo, RepoTable, DetailsExamples } from "../../components/images/origins/dockerfile/repo";

# DockerFile Origin Details

<p>
  Generally a <code>docker-file</code> image source would need to have information about a repo or a url endpoint where a tar.gz package was being served. However, when importing a stack file on Cycle, generally a user will do so through a
  git repo. For <code>docker-file</code> image source's, this repo information is used when both the repo and targz_url are not used in the details and is why neither is marked as required.
</p>
<AutoTable tablevalues={Details.dockerfile.shared} />

### Image Origin Details (Existing)

Any image origin type can use the existing object to define the use of an existing Cycle image source resource. Alongside the `existing` field, the user can also fill in any other fields in the details object based on the type of the `existing` resource. Any fields defined in the stack will override the fields set in the existing resource.

| Field    | Type   | Required | Description                                                                        |
| -------- | ------ | :------: | ---------------------------------------------------------------------------------- |
| existing | object |    ❌    | An object holding a source ID for an image source already defined on the platform. |

| Field     | Type   | Required | Description                                             |
| --------- | ------ | :------: | ------------------------------------------------------- |
| source_id | string |    ✅    | The source ID for the existing image source to be used. |

## Dockerfile Origin Object: Details

The `docker-file` image origin type is incredibly flexible and powerful.

<RepoTable />

<DetailsExamples />

### Using The Repo Field

If the stack references an image source, which resides in a different remote git repository, the repo field is used.

<RemoteRepo />

### Using The `targz_url` Field

Some users prefer to host packaged files on an endpoint for their image sources. If the targz_url is used, it must include the protocol of `http` or `https` along with the full url and endpoint in one string.

Along with that string, a user will provide the context directory and buildfile, unless those two values are root `/` and `/Dockerfile` respectively as it relates to the downloaded package, after being unzipped.

A `docker-file` image source may still rely upon registry credentials to authenticate during image create, if the image being created uses a parent image requiring authentication to download.

A user will NEVER use both the repo object and the targz_url in the same details object.

<details>
    <summary>Show TarGZ Example Again</summary>

```json
{
  "type": "docker-file",
  "details": {
    "targz_url": "https://yoururl.com/endpoint",
    "context_dir": "/target/directory",
    "build_file": "/target/directory/Dockerfile",
    "credentials": [
      {
        "url": "privateregistry.io",
        "username": "username",
        "token": "1231-4562-7556"
      },
      {
        "url": "privateregistry2.io",
        "username": "username2",
        "token": "1231-3362-7556"
      }
    ]
  }
}
```

</details>

### Context Directory

The context directory field `context_dir`, is used to explicitly state the context to be used during image create.

Using this partial Dockerfile and file tree as an example:

```Dockerfile
FROM node:alpine3.13

COPY ./package*.json ./
```

```bash
.
+-- package.json
+-- package-lock.json
+-- Dockerfile
+-- src
|   +-- index.js
|   +-- otherfile.js
+-- node_modules
```

The context directory that should be targeted in this example is `/`. This is desirable because the files referenced in the `COPY` command would be correctly found in that context.

If the context directory were to be set to `/src`, Cycle would look inside the source directory when trying to perform the COPY command, which has no files that start with `package` or that end in `.json`.

### Build File

Using that same idea, the build file `build_file` field is the full path to the file that will be used for building the image. In most cases, this file is named `Dockerfile` but regardless of the name all that is needed is the full path from the root directory to the file itself.

In the above example this would have been: `/Dockerfile`

### Registry Credentials

In some builds, there is a reference to a private image. Those private images require authentication before the files can be pulled. In order to facilitate this use the `credentials` field and list all necessary authentication objects needed by the image.

For example, there may be an image hosted on a private Docker registry with the following values:

- The `url` where the registry is hosted is `privateregistry.io`.
- The `username` to use for authentication is `username`.
- The `token` is `1231-5462-7556

```jsx

"credentials": [
  {
    "url": "privateregistry.io",
    "username": "username",
    "token": "1231-4562-7556"
  }
]

```
